import 'dart:async';

import 'package:flutter/material.dart';
import 'package:self_testing/src/report_generator.dart';
import 'package:self_testing/src/testing_report_models.dart';

import 'widgets/report_header_widgets.dart';
import 'widgets/scenario_card_widgets.dart';

/// A Flutter page that displays testing results matching the HTML report style.
class TestingReportPage extends StatefulWidget {
  const TestingReportPage({super.key});

  @override
  State<TestingReportPage> createState() => _TestingReportPageState();
}

class _TestingReportPageState extends State<TestingReportPage> {
  TestingReportData? _reportData;
  String? _errorMessage;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    unawaited(_loadReport());
  }

  Future<void> _loadReport() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final data = await ReportGenerator.loadReportData();
      setState(() {
        _reportData = data;
        _isLoading = false;
      });
    } on Object catch (error) {
      setState(() {
        _errorMessage = error.toString();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [Color(0xFF667eea), Color(0xFF764ba2)],
          ),
        ),
        child: SafeArea(
          child: _buildBody(),
        ),
      ),
    );
  }

  Widget _buildBody() {
    if (_isLoading) {
      return const Center(
        child: CircularProgressIndicator(color: Colors.white),
      );
    }

    if (_errorMessage != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Card(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.error_outline, size: 64, color: Colors.red),
                  const SizedBox(height: 16),
                  const Text(
                    'Failed to load report',
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  Text(_errorMessage!, textAlign: TextAlign.center),
                  const SizedBox(height: 24),
                  ElevatedButton.icon(
                    onPressed: _loadReport,
                    icon: const Icon(Icons.refresh),
                    label: const Text('Retry'),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    }

    final report = _reportData;
    if (report == null || report.scenarios.isEmpty) {
      return const Center(
        child: Card(
          margin: EdgeInsets.all(24),
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.inbox_outlined, size: 64, color: Colors.grey),
                SizedBox(height: 16),
                Text(
                  'No test scenarios found',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                SizedBox(height: 8),
                Text(
                  'Run some tests to see results here',
                  style: TextStyle(color: Colors.grey),
                ),
              ],
            ),
          ),
        ),
      );
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        ReportHeader(data: report),
        const SizedBox(height: 16),
        ...report.scenarios.map((scenario) => ScenarioCard(scenario: scenario)),
        const SizedBox(height: 32), // 2rem
        Center(
          child: Text(
            'Generated by Flutter Self Testing Framework',
            style: TextStyle(
              color: Colors.white.withValues(alpha: 0.8),
              fontSize: 12.8, // 0.8rem
            ),
          ),
        ),
        const SizedBox(height: 16),
      ],
    );
  }
}
