import 'package:self_testing/src/templates/report_scripts.dart';
import 'package:self_testing/src/templates/report_styles.dart';

String htmlTemplate({
  required String runStartLabel,
  required String runEndLabel,
  required int totalScenarios,
  required int totalTests,
  required int passedTests,
  required int failedTests,
  required String successRate,
  required String totalDurationLabel,
  required String goldenStatCard,
  required String scenarioCards,
}) =>
    '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Report - Flutter Self Testing</title>
    <style>
        ${reportStyles()}
    </style>
</head>
<body>
    <div class="container">
        ${_buildHeader(
      runStartLabel: runStartLabel,
      runEndLabel: runEndLabel,
      totalScenarios: totalScenarios,
      totalTests: totalTests,
      passedTests: passedTests,
      failedTests: failedTests,
      successRate: successRate,
      totalDurationLabel: totalDurationLabel,
      goldenStatCard: goldenStatCard,
    )}

        <div class="scenario-list">
            $scenarioCards
        </div>

        ${_buildFooter()}
    </div>

    ${_buildModal()}

    <script>
        ${reportScripts()}
    </script>
</body>
</html>
''';

String _buildHeader({
  required String runStartLabel,
  required String runEndLabel,
  required int totalScenarios,
  required int totalTests,
  required int passedTests,
  required int failedTests,
  required String successRate,
  required String totalDurationLabel,
  required String goldenStatCard,
}) =>
    '''
<div class="header">
    <div class="header-top">
        <h1>Flutter Self Testing Report</h1>
        <div class="header-timestamps">
            <div class="header-chip">
                <span class="chip-label">Run Start</span>
                <span class="chip-value">$runStartLabel</span>
            </div>
            <div class="header-chip">
                <span class="chip-label">Run End</span>
                <span class="chip-value">$runEndLabel</span>
            </div>
        </div>
    </div>
    ${_buildStats(
      totalScenarios: totalScenarios,
      totalTests: totalTests,
      passedTests: passedTests,
      failedTests: failedTests,
      successRate: successRate,
      totalDurationLabel: totalDurationLabel,
      goldenStatCard: goldenStatCard,
    )}
</div>
''';

String _buildStats({
  required int totalScenarios,
  required int totalTests,
  required int passedTests,
  required int failedTests,
  required String successRate,
  required String totalDurationLabel,
  required String goldenStatCard,
}) =>
    '''
<div class="stats">
    <div class="stat-card">
        <h3>$totalScenarios</h3>
        <p>Total Scenarios</p>
    </div>
    <div class="stat-card">
        <h3>$totalTests</h3>
        <p>Total Steps</p>
    </div>
    <div class="stat-card passed">
        <h3>$passedTests</h3>
        <p>Steps Passed</p>
    </div>
    <div class="stat-card failed">
        <h3>$failedTests</h3>
        <p>Steps Failed</p>
    </div>
    <div class="stat-card">
        <h3>$successRate%</h3>
        <p>Success Rate</p>
    </div>
    <div class="stat-card">
        <h3>$totalDurationLabel</h3>
        <p>Total Duration</p>
    </div>
    $goldenStatCard
</div>
''';

String _buildFooter() => '''
<div class="footer">
    <p>🚀 Generated by Flutter Self Testing Framework</p>
</div>
''';

String _buildModal() => '''
<div class="modal" id="screenshotModal" onclick="closeModal()">
    <span class="modal-close">&times;</span>
    <img class="modal-content" id="modalImage">
</div>
''';
